apiVersion: v1
kind: Service
metadata:
  name: es-lb-svc
  labels:
    app: es-lb-svc
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP